version: '3.7'

services:
  app:
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    restart: always
    container_name: app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_DEBUG_PORT}:${SERVER_DEBUG_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - web_network
    depends_on:
      - postgres
      - redis
  redis:
    container_name: redis
    image: redis:6
    networks:
      - web_network
  postgres:
    container_name: postgres
    image: postgres:13
    networks:
      - web_network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/data
networks:
  web_network:
volumes:
  pg_data:
